### ISSUE TITLE
Make better project structure

### ISSUE THREAD

**Issue by ghost** [soryncrash13/2dAdventure#1]
You should consider adding a "src" folder where everything should be put in subdirectories(if needed). 
Also please rename your files eg: "Form1.cs", to something which has more meaning since it can be confusing for someone who has not idea whatsoever about your project.

**Comment by sorinmiroiu97** [comment]
Will do. As I said the project is still in progress, in its pre-alpha-unreleased-ever-ever version... I still have a lot to do. I will rename everything once I'll add the other forms and classes for the project.

**Comment by ghost** [comment]
I would suggest to add to these: https://github.com/soryncrash13/2dAdventure/blob/master/src/Game.cs#L26-L29 
the private keyword to make it more clear eg: In Java they would have been public by default.
Also you might want to make these: https://github.com/soryncrash13/2dAdventure/blob/master/src/Game.cs#L28-L29 
"float" instead of "int" to have more precision over your "physics" system.

**Comment by sorinmiroiu97** [comment]
I'm gonna make those variables float, and those are by default private so there's no need to add the keyword, but I'll add it for more clarity. I'm still working with the collisions. They work just fine, but I want to use some other "mechanics" to say so for them. I think I'm gonna change the collisions today.

**Comment by ghost** [comment]
You might want to add: velocity, friction, dynamic and static objects and if you feel fancy about it kinematic objects are welcomed too :)
I can provide you some code but in Lua if you feel interested.

**Comment by sorinmiroiu97** [comment]
I'd like that, yeah 😃 . I'll more things but firstly I have to make the movements, jump and the collisions more acurate. Well I made them today. I just have to put each one of them into a method in the main.cs so I can just call them in every form. I think I'm gonna update the code tonight. I'll call you when I do this. 💃 😆

**Comment by ghost** [comment]
https://github.com/soryncrash13/2dAdventure/blob/master/src/Game.cs#L81 - Better use ArrayList because you want to be able to dynamically allocate memory for each bullet.
Also if I were you I'd start to move some code from Game.cs.

**Comment by sorinmiroiu97** [comment]
I'll move the code and make it cleaner, but first, as I told you I just want to finish all the assets for the game. Also I have to make the animations for the enemy too...hate that, but you gotta do what you've gotta do.

**Comment by ghost** [comment]
It was just a reminder :P
